#!/bin/sh

BATMAN_NEIGHBOURS_GROUP="batman-neighbours"
DOCKER_GROUP="docker"
P2P_INDUSTRIES_USER="p2p-industries"

create_user() {
    adduser --system --home /home/${P2P_INDUSTRIES_USER} --group ${P2P_INDUSTRIES_USER}
    adduser ${P2P_INDUSTRIES_USER} ${BATMAN_NEIGHBOURS_GROUP}
    adduser ${P2P_INDUSTRIES_USER} ${DOCKER_GROUP}
}

case "$1" in
configure)
    create_user
    ;;
esac

#DEBHELPER#
