[tool.poetry]
name = "simple-client"
version = "0.1.0"
description = ""
authors = ["Josef Zoller <josef@walterzollerpiano.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
hyveos-sdk = { path = "../../../sdks/python" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
