[package]
name = "hyveos-ifaddr"
version = "0.1.0"
edition = "2021"
rust-version = { workspace = true }
publish = { workspace = true }
license = { workspace = true }

[dependencies]
libc = { workspace = true }
multiaddr = { workspace = true }
thiserror = { workspace = true }
