[package]
name = "hyveos-ifaddr"
version = "0.1.0"
edition = "2021"
rust-version = { workspace = true }
publish = { workspace = true }
license = "GPL-3"

[dependencies]
libc = "0.2.153"
multiaddr = { workspace = true }
thiserror = { workspace = true }
