[package]
name = "hyvectl"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
publish.workspace = true

[dependencies]
clap = { workspace = true }
p2p-industries-sdk = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "rt-multi-thread"] }
futures = { workspace = true }
async-trait = "*"