[workspace]
members = ["libp2p/batman-adv", "engine"]
default-members = ["engine"]
resolver = "2"

[workspace.dependencies]
libp2p = { version = "0.53.2", features = ["tokio"] }
tokio =  { version = "1.37" }
thiserror = { version = "1" }
tokio-stream = { version = "0.1.15" }
rand = { version = "0.8.5" }

