[workspace]
members = [
    "crates/batman-neighbours-core",
    "crates/batman-neighbours-daemon",
    "crates/libp2p/batman-adv",
    "crates/stack",
    "crates/macaddress",
    "crates/ifaddr",
    "sdks/rust",
]
default-members = ["crates/batman-neighbours-daemon", "crates/stack"]
resolver = "2"

[workspace.package]
rust-version = "1.77.0"

[workspace.dependencies]
anyhow = { version = "1.0.82" }
libp2p = { version = "0.53.2", features = ["tokio"] }
libp2p-quic = { version = "0.10.2", git = "ssh://git@github.com/p2p-industries/libp2p-quic.git", rev = "a977b79242091a338e7ccc411f5878b8c5fccce6" }
libp2p-stream = { version = "0.1.0-alpha.1" }
netlink-packet-core = { version = "0.7.0" }
tokio = { version = "1.37" }
tokio-stream = { version = "0.1.15", features = ["net", "sync"] }
tokio-util = { version = "0.7.11" }
thiserror = { version = "1" }
tracing = { version = "0.1.40" }
rand = { version = "0.8.5" }
tarpc = { version = "0.34.0" }
serde = { version = "1.0.202", features = ["derive", "rc"] }
batman-neighbours-core = { version = "0.1.0", path = "crates/batman-neighbours-core" }
batman-neighbours-daemon = { version = "0.1.0", path = "crates/batman-neighbours-daemon" }
p2p-industries-sdk = { version = "0.1.0", path = "sdks/rust" }
stack = { version = "0.1.0", path = "crates/stack" }
libp2p-batman-adv = { version = "0.1.0", path = "crates/libp2p/batman-adv" }
ifaddr = { version = "0.1.0", path = "crates/ifaddr" }
macaddress = { version = "0.1.0", path = "crates/macaddress" }
prost = "0.12"
tonic = "0.11.0"
tonic-build = { version = "0.11.0", features = ["prost"] }

[profile.perf]
inherits = "release"
lto = true
codegen-units = 1
strip = true

[profile.size]
inherits = "perf"
opt-level = "z"
