[package]
name = "p2p-industries-sdk"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
prost = "0.12"
tonic = "0.11.0"

[build-dependencies]
tonic-build = { version = "0.11.0", features = ["prost"] }
