[package]
name = "p2p-industries-sdk"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
license = "MIT or Apache-2.0"

[dependencies]
prost = { workspace = true }
tonic = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
