[package]
name = "stack"
version = "0.1.0"
edition = "2021"
rust-version = { workspace = true }

[dependencies]
libp2p-batman-adv = { workspace = true, optional = true }
libp2p = { workspace = true, features = [
    "tokio",
    "identify",
    "kad",
    "gossipsub",
    "ping",
    "macros",
    "ed25519",
    "serde",
    "request-response",
    "cbor",
] }
libp2p-quic = { workspace = true, features = ["tokio"] }
libp2p-stream = { workspace = true }
tokio = { workspace = true, features = [
    "fs",
    "rt-multi-thread",
    "macros",
    "sync",
    "io-std",
    "io-util",
] }
tokio-util = { workspace = true, features = ["compat"] }
thiserror = { workspace = true }
void = "1.0.2"
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tokio-stream = { workspace = true, features = ["fs"] }
rustyline = { version = "14.0.0", features = ["derive"] }
anyhow = { workspace = true }
patricia_tree = "0.8.0"
serde = { workspace = true }
rand = { workspace = true }
macaddress = { workspace = true }
prost = { workspace = true }
tonic = { workspace = true }
futures = "0.3.30"
clap = { version = "4.5.4", features = ["derive"] }
netdev = "0.25.0"
ifaddr = { workspace = true }
asynchronous-codec = { version = "0.7.0", features = ["cbor"] }
ulid = { version = "1.1.2", features = ["serde"] }
sha2 = { version = "0.10.8", features = ["asm"] }
base64-simd = "0.8.0"
dashmap = "5.5.3"
pin-project = "1.1.5"
async-once-cell = "0.5.3"
arboard = { version = "3.4.0", optional = true }
console-subscriber = { version = "0.2.0", optional = true }
bytes = "1.6.0"
indicatif = { version = "0.17.8", features = ["tokio", "in_memory"] }
dirs = "5.0.1"
regex = { version = "1.10.4", default-features = false, features = [
    "perf",
    "std",
] }
cbor4ii = { version = "0.3.2", optional = true }
drop-stream = "0.3.0"

[build-dependencies]
tonic-build = { workspace = true }

[features]
batman = ["dep:libp2p-batman-adv", "dep:cbor4ii"]
location = []
mdns = ["libp2p/mdns"]
clipboard = ["dep:arboard"]
console-subscriber = ["dep:console-subscriber"]
