[package]
name = "libp2p-batman-adv"
version = "0.1.0"
edition = "2021"
rust-version = { workspace = true }
authors = ["Josef Zoller <josef@walterzollerpiano.com>"]

[dependencies]
batman-neighbours-core = { workspace = true }
bincode = "1.3.3"
futures = { workspace = true }
hashlink = "0.9.0"
ifaddr = { workspace = true }
itertools = "0.12.1"
libp2p = { workspace = true, features = ["serde"] }
macaddress = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
socket2 = "0.5.7"
tarpc = { workspace = true, features = [
    "serde-transport",
    "serde-transport-bincode",
    "unix",
] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros"] }
tokio-stream = { workspace = true, features = ["sync"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
void = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
netlink-proto = "0.11.3"
netlink-packet-core = { workspace = true }
netlink-packet-route = "0.19.0"
rtnetlink = "0.14.1"
