[package]
name = "hyveos-libp2p-batman-adv"
version = "0.1.0"
edition = "2021"
authors = ["Josef Zoller <josef@walterzollerpiano.com>"]
rust-version = { workspace = true }
publish = { workspace = true }

[dependencies]
batman-neighbours-core = { workspace = true }
bincode = "1.3.3"
futures = { workspace = true }
hashlink = "0.9.0"
hyveos-ifaddr = { workspace = true }
hyveos-ifwatcher = { workspace = true }
itertools = "0.13.0"
libc = "0.2.153"
libp2p = { workspace = true, features = ["serde"] }
hyveos-macaddress = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
socket2 = "0.5.7"
tarpc = { workspace = true, features = [
    "serde-transport",
    "serde-transport-bincode",
    "unix",
] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros"] }
tokio-stream = { workspace = true, features = ["sync"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
