[package]
name = "hyveos-libp2p-addr-filter"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
publish.workspace = true

[dependencies]
libp2p = { workspace = true }
tracing = { workspace = true }
