name: Frontend

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Frontend checks
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: ui/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm i
        working-directory: ui

      - name: Check
        run: pnpm check
        working-directory: ui

      - name: Lint
        run: pnpm lint
        working-directory: ui

      - name: Build
        run: pnpm build
        working-directory: ui
