name: Label issues
on:
  issues:
    types:
      - opened
      - reopened
      - edited

jobs:
  label_issues:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    permissions:
      issues: write
    steps:
      - run: gh issue edit "$NUMBER" --add-labels "$LABELS"
        if:  ${{ startsWith(github.event.issue.title, 'Tracking') }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: tracking
