name: Automated release

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-latest-release-number:
    name: Get latest release number
    runs-on: ubuntu-24.04
    if: github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'CI')
    outputs:
      old_version: ${{ steps.latest_number.outputs.old_version }}
      new_version: ${{ steps.increment_version.outputs.new_version }}
      number: ${{ steps.increment_version.outputs.number }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get latest release tag
        id: latest_number
        run: |
          number=$(gh release list --json tagName --jq '[.[].tagName | capture("^v(?<number>[0-9]+)-rolling$").number][0]')
          echo "Current number: $number"
          echo "number=$number" >> $GITHUB_ENV
          echo "old_version=v${number}-rolling" >> $GITHUB_OUTPUT

      - name: Increment version number
        id: increment_version
        run: |
          new_number=$(( ${{ env.number }} + 1))
          new_version="v${new_number}-rolling"
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_ENV
          echo "new_version=$new_version" >> $GITHUB_OUTPUT
          echo "number=$new_number" >> $GITHUB_OUTPUT

  extract-debian-packages:
    name: Extract debian packages
    runs-on: ubuntu-24.04
    if: github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'CI')
    outputs:
      crates: ${{ steps.cargo-metadata.outputs.crates }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@d8352f6b1d2e870bc5716e7a6d9b65c4cc244a1a
        with:
          toolchain: stable

      - id: cargo-metadata
        run: |
          DEBIAN_PACKAGES=$(cargo metadata --no-deps --format-version=1 | jq -c '[.packages[] | select(.metadata.deb) | {name, version, deb_name: (.metadata.deb.name // .name)}]')
          echo "crates=$DEBIAN_PACKAGES" >> $GITHUB_OUTPUT

  build-debian:
    name: Build debian package ${{ matrix.crate.deb_name }} for ${{ matrix.target.arch }}
    runs-on: ubuntu-24.04
    if: github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'CI')
    needs:
      - extract-debian-packages
      - get-latest-release-number
    env:
      GH_TOKEN: ${{ github.token }}
      POSTHOG_TOKEN: ${{ secrets.POSTHOG_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        crate: ${{ fromJSON(needs.extract-debian-packages.outputs.crates) }}
        target:
          - target: x86_64-unknown-linux-gnu
            arch: amd64
          - target: aarch64-unknown-linux-gnu
            arch: arm64
    steps:
      - uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: taiki-e/cache-cargo-install-action@caa6f48d18d42462f9c30df89e2b4f71a42b7c2c
        with:
          tool: cargo-deb

      - name: Install cross compile linker
        if: ${{ matrix.target.arch == 'arm64' }}
        uses: awalsh128/cache-apt-pkgs-action@a6c3917cc929dd0345bfb2d3feaf9101823370ad # v1.4.2
        with:
          packages: gcc-aarch64-linux-gnu
          version: 1.0

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target.target }}--${{ matrix.crate.name }}

      - name: Calculate revision number
        run: |
          version_and_rev=$(gh release view --json assets --jq '.assets[].name | capture("^${{ matrix.crate.deb_name }}_(?<version>[0-9]+.[0-9]+.[0-9]+)-(?<rev>[0-9]+)_${{ matrix.target.arch }}.deb$") | {version, rev}' ${{ needs.get-latest-release-number.outputs.old_version }})
          version=$(echo $version_and_rev | jq -r '.version')
          rev=$(echo $version_and_rev | jq -r '.rev')
          if [ "$version" == "${{ matrix.crate.version }}" ]; then
            rev=$(( $rev + 1 ))
          else
            rev=1
          fi
          echo "Revision number: $rev"
          echo "rev=$rev" >> $GITHUB_ENV

      - name: Build debian package
        run: cargo deb -p ${{ matrix.crate.name }} --deb-revision ${{ env.rev }} --target ${{ matrix.target.target }}

      - name: Upload artifacts
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.crate.name }}--${{ matrix.target.arch }}.deb
          path: target/${{ matrix.target.target }}/debian/*.deb

  create-release:
    name: Create a release
    runs-on: ubuntu-24.04
    if: github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'CI')
    needs:
      - get-latest-release-number
      - build-debian
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: write
      attestations: read
    steps:
      - name: Install APT packages
        uses: awalsh128/cache-apt-pkgs-action@a6c3917cc929dd0345bfb2d3feaf9101823370ad # v1.4.2
        with:
          packages: apt-utils
          version: 1.0

      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4 # v6.1.0
        with:
          gpg_private_key: ${{ secrets.APT_REPO_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.APT_REPO_GPG_PRIVATE_KEY_PW }}

      # For each combination of crate and target download the artifact
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: apt-repo
          pattern: "*--*.deb"
          merge-multiple: true

      - name: List packages
        run: ls -R ./apt-repo/

      - name: Create repository
        run: |
          cd apt-repo
          dpkg-scanpackages -m . > Packages
          sed -i Packages -e 's|Filename: \./|Filename: |'
          gzip -k -f Packages
          touch Release
          echo "Origin: P2P Industries Repository" >> Release
          echo "Label: unstable"  >> Release
          echo "Suite: unstable" >> Release
          echo "Codename: unstable" >> Release
          echo "Architectures: amd64 arm64" >> Release
          echo "components: main" >> Release
          apt-ftparchive release . >> Release
          gpg --default-key ${{ steps.import-gpg.outputs.keyid }} -abs -o - Release > Release.gpg
          gpg --default-key ${{ steps.import-gpg.outputs.keyid }} --clearsign -o - Release > InRelease

      - name: Create release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # 2.0.8
        with:
          tag_name: ${{ needs.get-latest-release-number.outputs.new_version }}
          make_latest: true
          files: ./apt-repo/*
          name: Rolling release (${{ needs.get-latest-release-number.outputs.number }})
          generate_release_notes: true
          draft: ${{ github.event_name != 'push' }}
