[tool.poetry]
name = "simple-listsner"
version = "0.1.0"
description = ""
authors = ["Josef Zoller <josef@walterzollerpiano.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
p2pindustries = { path = "../../../sdks/python" }
grpcio = "^1.64.0"
protobuf = "^5.27.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
